export const GET_CATEGORY_FROM_BUTTON = 'GET_CATEGORY_FROM_BUTTON';
export const DELETE_CATEGORY_FROM_BUTTON = 'DELETE_CATEGORY_FROM_BUTTON';

export const GET_SUBCATEGORY_FROM_BUTTON = 'GET_SUBCATEGORY_FROM_BUTTON';
export const DELETE_SUBCATEGORY_FROM_BUTTON = 'DELETE_SUBCATEGORY_FROM_BUTTON';

export const SHOW_CATEGORY_CARDS = 'SHOW_CATEGORY_CARDS';
